project:
  type: website
  output-dir: docs

website:
  title: "Kai"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects
      - href: datavisualisation.qmd
        text: Visualisations
      - href: Reflection.qmd
        text: Reflection

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css




